- name: install nginx
  become: yes
  yum: name=nginx state=present

- name: change port to 8080
  become: yes
  template: 
    src: nginx.conf
    dest: /etc/nginx/conf.d/default.conf
  register: state
- debug: msg="{{state}}"

- name: Restart nginx
  become: yes
  service: name=nginx state=restarted
  when: state.changed

- name: run nginx
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes