- name: install nodejs an nginx
  become: yes
  yum: name={{item}} state=present
  with_items:
    - nginx

- name: check config
  become: yes
  command: chkconfig nginx on

- name: change port to 8080
  become: yes
  copy: 
    src: ../../../nginx.conf
    dest: /etc/nginx/conf.d/default.conf

- name: run nginx
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes