- name: install nginx
  become: yes
  yum: name=nginx state=present

- name: change port to {{nginx_port}}
  become: yes
  template: 
    src: nginx.conf
    dest: /etc/nginx/conf.d/default.conf
  register: nginx_config_change_result

- set_fact:
    nginx_conf_result: "{{nginx_config_change_result.changed}}"
- debug:
    var: nginx_conf_result


- name: Restart nginx
  become: yes
  service: name=nginx state=restarted
  when: nginx_config_change_result.changed

- name: run nginx
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes