- name: install nginx
  become: yes
  yum: name=nginx state=present
  notify: Restart nginx

- name: change port to 8080
  become: yes
  template: 
    src: nginx.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: Restart nginx
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: run nginx
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes