---
- hosts: webserver1
  vars_files:
    - ./configs/webserver1.yml
  tasks:
    - name: debug variable
      debug:
        var: nginx_conf_result
  roles:
    - nginx
    - nodejs


- hosts: webserver2
  vars_files:
    - ./configs/webserver2.yml
  roles:
    - nodejs