---
- hosts: all
  tasks:
    - name: add repo
      become: yes
      yum_repository:
        name: nodejs 
        description: node from rpm
        baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
        gpgcheck: no

- hosts: webservers
  vars:
    node_version1: 7.9.0 
  tasks:
    - name: install nodejs an nginx
      become: yes
      vars:
        node_version: 7.9.0
      yum: name={{item}} state=present
      with_items:
        - nginx
        - nodejs-{{node_version}}

    - name: check config
      become: yes
      command: chkconfig nginx on

    - name: change port to 8080
      become: yes
      copy: 
        src: ./nginx.conf
        dest: /etc/nginx/conf.d/default.conf

    - name: run nginx
      become: yes
      service:
        name: nginx
        state: restarted
        enabled: yes
    - debug:
        msg: "hey{{node_version1}}"
- hosts: webservers2
  tasks:
    - name: install nodejs
      become: yes
      yum:
        name: nodejs
        state: latest


