- name: add repo
  become: yes
  yum_repository:
    name: nodejs 
    description: node from rpm
    baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
    gpgcheck: no

- name: install nodejs
  become: yes
  yum:
    name: nodejs-{{node_version}}
    state: present
- debug:
    var: nginx_conf_result
